ci: refactor _run-clang-tools.yaml

diff --git a/.github/workflows/_run-clang-tools.yaml b/.github/workflows/_run-clang-tools.yaml
--- a/.github/workflows/_run-clang-tools.yaml
+++ b/.github/workflows/_run-clang-tools.yaml
@@ -24,16 +24,55 @@ defaults:
 
 jobs:
   check-want-lint:
-    if: ${{ !github.event.pull_request.draft }}
+    if: ${{ !github.event.pull_request.draft && github.triggering_actor != 'dependabot[bot]' }}
     uses: ./.github/workflows/_check-want-test.yaml
     with:
       keyword: "lint"
 
-  verify-format-and-lint:
+  format-and-lint-changed:
+    runs-on: ubuntu-latest
+    needs: [check-want-lint]
+    if: ${{ inputs.files-changed-only && (inputs.force || needs.check-want-lint.outputs.want-test == 'true') }}
+
+    steps:
+      - run: sudo apt-get install -y libeigen3-dev
+
+      - uses: lukka/get-cmake@latest
+        with:
+          cmakeVersion: "~3.16.0" # for Ubuntu 20.04
+
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - name: Configure with cmake
+        run: |
+          cmake \
+            -DCMAKE_BUILD_TYPE=Release \
+            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
+            -S . -B build -G Ninja
+
+      - uses: cpp-linter/cpp-linter-action@v2
+        id: clang-tools
+        with:
+          version: ${{ inputs.version }}
+          extensions: "cpp,hpp,c,h"
+          style: file
+          tidy-checks: ""
+          database: build
+          ignore: ".github|build|third-party|test"
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+
+      - name: Fail fast
+        if: ${{  steps.clang-tools.outputs.checks-failed > 0 }}
+        run: echo "Some files failed the linting checks!" && exit 1
+
+  format-and-lint-all:
     # runs-on: ubuntu-latest
     runs-on: [self-hosted, sandbox]
     needs: [check-want-lint]
-    if: ${{ github.triggering_actor != 'dependabot[bot]' && (inputs.force || needs.check-want-lint.outputs.want-test == 'true') }}
+    if: ${{ !inputs.files-changed-only && (inputs.force || needs.check-want-lint.outputs.want-test == 'true') }}
 
     steps:
       # - run: sudo apt-get install -y libeigen3-dev
@@ -54,7 +93,6 @@ jobs:
             -S . -B build -G Ninja
 
       - name: Run clang tools to all files
-        if: ${{ always() && !inputs.files-changed-only }}
         run: |
           # wget https://apt.llvm.org/llvm.sh
           # chmod +x llvm.sh
@@ -66,20 +104,3 @@ jobs:
           # sudo ln -sf clang-format-$VERS /usr/bin/clang-format
 
           ./scripts/run_clang_tools.sh -c
-
-      - uses: cpp-linter/cpp-linter-action@v2
-        if: ${{ always() && inputs.files-changed-only }}
-        id: clang-tools
-        with:
-          version: ${{ inputs.version }}
-          extensions: "cpp,hpp,c,h"
-          style: file
-          tidy-checks: ""
-          database: build
-          ignore: ".github|build|third-party|test"
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
-
-      - name: Fail fast
-        if: ${{ always() && steps.clang-tools.outputs.checks-failed > 0 }}
-        run: echo "Some files failed the linting checks!" && exit 1
