ci(gha): refactor actions

diff --git a/.github/workflows/pr-test.yaml b/.github/workflows/pr-test.yaml
--- a/.github/workflows/pr-test.yaml
+++ b/.github/workflows/pr-test.yaml
@@ -22,15 +22,27 @@ defaults:
 
 jobs:
   check-want-test:
-    if: ${{ !github.event.pull_request.draft }}
     uses: ./.github/workflows/_check-want-test.yaml
 
   test-and-coverage:
-    needs: [check-want-test]
-    if: ${{ always() && needs.check-want-test.outputs.want-test == 'true' }}
+    needs: check-want-test
+    if: ${{ needs.check-want-test.outputs.want-test == 'true' }}
     uses: ./.github/workflows/_test-and-coverage.yaml
     secrets:
       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+
+  conclusion:
+    needs: test-and-coverage
+    runs-on: ubuntu-latest
+    if: ${{ always() }}
+    steps:
+      - run: |
+          if [[ $FAILED == 'true' ]]; then
+            echo "Test failed."
+            exit 1
+          fi
+        env:
+          FAILED: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
diff --git a/.github/workflows/pr-wheels.yaml b/.github/workflows/pr-wheels.yaml
--- a/.github/workflows/pr-wheels.yaml
+++ b/.github/workflows/pr-wheels.yaml
@@ -25,28 +25,25 @@ jobs:
     if: ${{ !github.event.pull_request.draft }}
     uses: ./.github/workflows/_check-want-test.yaml
 
-  build-base:
+  test-build-wheels:
     needs: check-want-test
     if: ${{ needs.check-want-test.outputs.want-test == 'true' }}
-    uses: ./.github/workflows/_base-build.yaml
-
-  test-build-linux:
-    needs: build-base
-    uses: ./.github/workflows/_wheel-build.yaml
+    uses: ./.github/workflows/wheels-matrix.yaml
     with:
-      python: cp38-manylinux_x86_64
+      minimal: true
 
-  test-build-mac-intel:
-    needs: build-base
-    uses: ./.github/workflows/_wheel-build.yaml
-    with:
-      python: cp38-macosx_x86_64
-
-  test-build-mac-arm:
-    needs: build-base
-    uses: ./.github/workflows/_wheel-build.yaml
-    with:
-      python: cp38-macosx_arm64
+  conclusion:
+    needs: test-build-wheels
+    runs-on: ubuntu-latest
+    if: ${{ always() }}
+    steps:
+      - run: |
+          if [[ $FAILED == 'true' ]]; then
+            echo "Linting failed."
+            exit 1
+          fi
+        env:
+          FAILED: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
